project_id = "tdmeripiyfocaexvoyiu"

[functions.process-document]
verify_jwt = true

[functions.generate-resume]
verify_jwt = true

[functions.chat-documents]
verify_jwt = true

[functions.analyze-resume]
verify_jwt = true

[functions.reformat-resume]
verify_jwt = true